### ISSUE TITLE
add polyfill for unsupported platform

### ISSUE THREAD

**Issue by darkskygit** [CertainLach/vmprotect#1]
now I will panic when I compile my project in m1.
can a polyfill be added to this crate at this time?
for example, passthrough the protected code and skip the link of dependent libraries
if needed, I can submit a pr

**Comment by CertainLach** [comment]
I think user code should be explicitly self-aware of opt-out vmprotect support. In the end, all required is `#[cfg_attr(feature = "vmp", protected(virtualize)]` in code, and 
```
[dependencies]
vmprotect = {optional=true}

[features]
vmp = ["vmprotect"]
```
In Cargo.toml
