### ISSUE TITLE
Upgrade to stable asm (Rust 1.59.0+)

### ISSUE THREAD

**Issue by Jakobzs** [CertainLach/vmprotect#2]
Hello,

Since Rust 1.59.0, `asm` has been stabilized and no longer needs `#![feature(asm)]`. I find that the project does not compile since I use the latest nightly at 1.64.0 at this time of writing.

To solve compiling for Rust 1.59.0 and up, `use std::arch::asm;` should be utilized in `lib.rs` over `#![feature(asm)]`.

**Comment by f1nzo** [comment]
same problem here, is there anyway to solve temporarily myself?

**Comment by Jakobzs** [comment]
> same problem here, is there anyway to solve temporarily myself?

Sorry for the late reply. You can make your own repo or use mine which fixes the issue, and then point to it with Cargo, until the author potentially addresses this issue. The reference commit is: https://github.com/Jakobzs/vmprotect/commit/f63cb23a88147f4938669e7207afe104a94819a4

**Comment by Jakobzs** [comment]
Closing this issue as my PR has been merged into master.
